language: node_js
node_js:
- '10

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: Z2cslmuvYBYfPoLdO9DNyOaLRGz6mlB3nC/pXS25KIR6FSk39uCaOEPdPUxffLpGGcm57P0EcOs9YUnaKNBVzJHfX+5X7F3gZlFgbq9an6ZHRNwN2pP0E4D0pEfO8BUh69AAuOiEP7oeHcaf+q35EI/Sciyo+xKGv+uZN3P7Kz1UAAruLbeXiJ0AcGYiXm/wnboJeJRF7+4pWQryNLTFqSVM9Tv8cYk7/XvZIx001PB2MNjMf51eLEVmjvrIcvv3rdXlrNuK2+RCSw7GCxweUmKXCms2UuMfbcB/IdZedU/TObeZBW90zDLRO8KxpiOzTr+ueXKFRYHhlyrAakubNZLbGqD20RMMqGWY5GGxZIBdfm+pJ5HSyYIll20ZsGxWoO7LKkzemAwr7Ik35ePILWyVZ/Tj+UFmpDXAK4F6cdV7PR83LDZy7Z8LMgbDFW3zjWpcSX7V1YTcHW7vghBzBKdkK6kcXm/Fgq5XkxdXlRDJ4HuZ3+mG21RqkPjgEEo9+ZCP9QM6UkkdkbE1aHI2BWTG/2rnhfa48vUNWYXkdrU03RGr/3cfGCM7jKwPyM5yQtezzUQBTs8sGQ5GIt5z39xwjsLj7NuFj2mIkmJ4xBX2kEoB6G01tsvL+LdutuNBzANPrscZuGUr6HR7H4e7tswXL0vnrw6sASkP2PKde0Y=